Repository miMeiner/NoteAgain, pull requests merged in 2022-12, with the labels that each got.

#11 Convert the project into TS
  App.js
  App.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: Function

#12 Firebase
  .gitignore
  App.tsx
  app.config.ts
  babel.config.js
  env.d.ts
  firebase/Hooks.ts
  firebase/firebaseConfig.ts
  metro.config.ts
  package-lock.json
  package.json
Labels: Database

#14 Create README.md
  README.md
Labels: Documentation

#21 5 create user collection
  .eslintrc.json
  App.tsx
  firebase/Hooks.ts
  types/FirebaseTypes.ts
Labels: Function, Database

#23 Add textcomponents with our desired font
  .eslintrc.json
  App.tsx
  assets/fonts/Sora-Bold.ttf
  assets/fonts/Sora-ExtraBold.ttf
  assets/fonts/Sora-ExtraLight.ttf
  assets/fonts/Sora-Light.ttf
  assets/fonts/Sora-Medium.ttf
  assets/fonts/Sora-Regular.ttf
  assets/fonts/Sora-SemiBold.ttf
  assets/fonts/Sora-Thin.ttf
  react-native.config.js
  src/utils/styles/FontStyles.tsx
Labels: Design

#32 Add navigation tabs at the bottom of the screen and update fonts
  App.tsx
  assets/fonts/Sora-Bold.ttf
  assets/fonts/Sora-ExtraBold.ttf
  assets/fonts/Sora-ExtraLight.ttf
  assets/fonts/Sora-Light.ttf
  assets/fonts/Sora-Medium.ttf
  assets/fonts/Sora-Regular.ttf
  assets/fonts/Sora-SemiBold.ttf
  assets/fonts/Sora-Thin.ttf
  package-lock.json
  package.json
  pages/Home.tsx
  pages/Login.tsx
  pages/Messages.tsx
  pages/New.tsx
  pages/Profile.tsx
  pages/Register.tsx
  pages/Saved.tsx
  react-native.config.js
  src/components/LoginForm.tsx
  src/components/NavBar.tsx
  src/components/RegisterForm.tsx
  src/components/ReminderCard.tsx
  src/components/small/FormButton.tsx
  src/utils/styles/FontStyles.tsx
Labels: Design, Function

#37 Fix the massive errors occuring when trying to compile
  App.tsx
  config/firebaseConfig.ts
  pages/Login.tsx
  pages/Register.tsx
  pages/Saved.tsx
  src/components/NavBar.tsx
  src/components/ReminderCard.tsx
  src/components/TodoCard.tsx
  src/components/TodoListCard.tsx
Labels: Bug

#44 41 implement create reminder function
  hooks/firebase/ReminderHooks.ts
  package-lock.json
  package.json
  pages/StartPage.tsx
  src/components/RegisterForm.tsx
  src/components/newModal/ModalContent.tsx
  src/components/newModal/NewReminder.tsx
  src/components/newModal/NewTodo.tsx
  src/components/small/FormButton.tsx
Labels: Function, Database

#45 6 link between user reminder
  App.tsx
  assets/images/exProfile.svg
  assets/images/logo.svg
  hooks/firebase/ReminderHooks.ts
  hooks/firebase/UserHooks.ts
  package-lock.json
  package.json
  pages/Login.tsx
  pages/StartPage.tsx
  src/auth/AuthContext.ts
  src/components/LoginForm.tsx
  src/components/NavBar.tsx
  src/components/RegisterForm.tsx
  src/components/ReminderCard.tsx
  src/components/SvgLibary.tsx
  src/components/TopBar.tsx
  src/components/small/FormButton.tsx
Labels: Function, Database
